# Snakemake configuration for postprocess workflow
sample_sheet: "src/SampleSheet_default.csv"
num_reads: 2
library_name: "xR077"
run: "xR077"
fastqdir: "output"
start_s: 1
dryrun: true
script_dir: "src/Tools"
script_path: "src/Tools/postprocess/postprocess_hiseq_lane_centos7_test_gzip.pl"
lanes: [1,2,3,4,5,6,7,8]
fastp_threads: 4
fastp_outdir: "results/fastp"
metadata: "metadata/251219_23G5F2LT3_10B_PE151_xR077.xlsx"
run_info_path: "src/RunInfo_nn.xml"
basecalls_path: "/staging/nextcloud/NovaseqX/20251219_LH00626_0085_A23G5F2LT3/Data/Intensities/BaseCalls"
data_dir: "/staging/nextcloud/NovaseqX/20251219_LH00626_0085_A23G5F2LT3"
tiles: ""
email_sender: "kstachel@uci.edu"
email_recipient: "kstachel@uci.edu"
email_cc: "kstachel@uci.edu"