# Snakemake configuration for postprocess workflow
sample_sheet: "src/SampleSheet_default.csv"
num_reads: 2
library_name: "mR489"
fastqdir: "output"
start_s: 1
lanes: [1,2,3,4,5,6,7,8]
fastp_threads: 4
fastp_outdir: "results/fastp"
metadata: "metadata/01162026_M4B2Y_MR489_v3_PE250.xlsx"
run_info_path: "src/RunInfo_nn.xml"
data_dir: "/staging/nextcloud/Miseq/260116_M05630_0704_000000000-M4B2Y"
tiles: ""
email_sender: "kstachel@uci.edu"
email_recipient: "kstachel@uci.edu"
email_cc: "kstachel@uci.edu"